### ISSUE TITLE
Candidate parameters

### ISSUE THREAD

**Issue by bpbond** [JGCRI/trackingC#12]
Taken from #6 and expanded.

Param | Definition | R settable? | Done
-- | -- | -- | --
Q10 | Rh temperature sensitivity | Yes | Yes
Beta | CO2 fertilization factor | Yes | Yes
ECS | Equilibrium climate sensitivity | Yes | Yes
AERO_SCALE | Aerosol forcing factor | Yes |  Yes
Keff | Ocean heat diffusivity | Yes |  Yes
TT | Thermohaline overturning factor | Yes |  
Scenario | SSP scenario | Yes |  
NPP0 | Preindustrial NPP | Yes | Yes

Notes
- Q10 - huge control on terrestrial sink, many papers (Friedlingstein, Bond-Lamberty, Reichstein group); lognormal
- Beta ("Second, CO2 fertilization and nitrogen deposition are the most important drivers of change" [source](https://www.nature.com/articles/s41598-020-66103-9)); normal
- ECS - many extremely well known papers on this: [one](http://dx.doi.org/10.1029/2019RG000678) [two](http://dx.doi.org/10.1038/ngeo337) [three](http://dx.doi.org/10.1126/science.1144735); lognormal
- AERO_SCALE - aerosol scaling factor - 
- Keff - ocean heat diffusivity - yes if possible! **Note: joint with ECS**
- Ocean temperature? Kalyn has recently updated, would be easy to add
- TT - thermohaline circulation factor - 
- Scenario - this is a different: first, a categorical variable, not continuous that will determine which INI file and/or core we use; and second moves us from the realm of model prediction uncertainty and/or sensitivity to the relative importance of emissions
- NPP0 - hmm best would be to use a mean & sd from CMIP6? For now could start with (55, 5) or something like that
 
Anything else?

**Comment by leeyap** [comment]
@bpbond 

Tabling `TT()` for now because the large value (and subsequently large SD) wasn't working.

Are there other parameters we want to implement? Other than `TT()`, all of the above are at least included with a normal dist and a 10% SD.

**Comment by bpbond** [comment]
Cool!

No, let's leave it at that for now. Tabling TT sounds good. Can't wait to see updated graphs :)
