### ISSUE TITLE
Code next-step suggestions

### ISSUE THREAD

**Issue by bpbond** [JGCRI/trackingC#19]
Hello @leeyap , some suggestions for your Friday morning :) 

- [x] The `params_PDFs` chunk should be re-thought. Rather than sequentially call `density`, I would suggest take `runlist`, drop the run_number column, `pivot_longer` so that you have param name in one column and param value in another, and then use ggplot + geom_density + facet_wrap(~param_name).
- [x] Let's start auto-numbering figures. You can use the `bookdown` package for this, and Kendal's code [here](https://github.com/COMPASS-DOE/rs-synthesis/blob/main/rs-synthesis.Rmd) has good examples of how to implement it.
- [x] In a similar vein: figure captions! Please draft captions (in the Rmd file) describing what each figure is showing.
- [x] The "Where does carbon end up?" figure is _lovely_ 🎉 . I would remove the facet labels (1, 2, 3, etc.) though, as they consume valuable space and don't give any useful information.
- [x] The "Parameter correlation" figure (see why we need figure numbering?) is also a work of art! 🥂  Consider making the density fills on the diagonal semi-transparent.
- [x] I suspect we'll want to add a version of Natanel's airborne fraction figure? Hmm, let's think about ways to visualize this.

**Comment by leeyap** [comment]
- [ ] New figure: temperature outputs compared to CMIP6 spread, linked to parameters
