### ISSUE TITLE
Initial steps from 2021-12-15 mtg

### ISSUE THREAD

**Issue by bpbond** [JGCRI/trackingC#2]
R to do:

- [x] Table with Hector parameter, median/default, standard deviation
- [x] Step to generate a run list—a data frame with (e.g.) run number, Q10 value, beta value

Science question: 

- Where does fossil fuel C end up and how does that change with changing parameter values (i.e. assumptions about earth system such as beta, Q10, etc)
- Could also reframe this a bit more broadly: how does model system C move around w/ different parameter values
- Can also potentially use comparisons with observational data to say something about likelihood of parameter values (kind of Bayesian-esque)
- …and thus likelihood of what the earth system functionality is (i.e. goal is not just to infer about Hector, but also real life)
- This would leverage a probabilistic (parametric) Monte Carlo approach — e.g. the PDFs of 5 key variables, if we’d like to draw 100 times from each 100^5 = 10^10! Too many :)  
- Key off of [Keenan et al.](https://www.nature.com/articles/s41586-021-04096-9) recent paper
- Keenan paper, [equivalent one](https://www.nature.com/articles/nature08930) for respiration, some of the probabilistic work noted above, airborne fraction

**Comment by bpbond** [comment]
Note also Chris's Python analysis — in Slack and somewhere on Github

**Comment by bpbond** [comment]
Short-term, "dead end" but still useful:
* Let's just look at 2100 for now — keep output data size much smaller
* Visualize the output as well as the inputs

**Comment by bpbond** [comment]
Next I would suggest we'd like to re-architect things to be more general.

## Generating the run list

Option 1 is the csv approach:
```r
paramlist <- read.csv("paramlist.csv")

runlist <- tibble(run_number = 1:n)
for each row in the paramlist {
 param_name <- paramlist$param_name[I]
 runlist[param_name] <- rnorm(n, paramlist$param_mu[i], paramlist$param_sigma[I])
}
```

Option 2 is simpler and doesn't involve a csv file:
```r
runlist <- tibble(
 run_number = 1:n,
 beta = rnorm(n, x, y),
 q10 = rnorm(n, x, y)
)
```

**Comment by bpbond** [comment]
## Running Hector

For each row of the runlist... (via `group_by`...`do`, `for`, `apply`) we'll call `run_hector()` with that row.

```r
run_hector <- function(pdata) {
 for( each column in pdata ) {
  # get the value and set is via `setvar`
}
 # run the hector code, get data, etc.
}
```

**Comment by bpbond** [comment]
@leeyap asks: what will be _next_ steps after this?

* Timing information. How long does n=10 take? n=100?
* Parameter side, we want to identify the candidate parameters we're going to be using and justify the choice. Then we'll want to do some research and reasonable PDFs for them (form: normal/lognormal/something else; mu and sigma)
* Parameter side, we'll want to think about _joint_ distributions. Do we want to define any? If so, which, and will need to implement that in code
* Output side, in Chris's Python analysis, he produced cool graphs of sensitivity over time. We're going to want to do something I similar
* Produce and refine visualizations and numerical summaries of outputs

**Comment by leeyap** [comment]
I think this is okay to be closed
