### ISSUE TITLE
High level plan

### ISSUE THREAD

**Issue by bpbond** [JGCRI/trackingC#3]
(all times are very tentative, just trying to organize mentally)

**January**

- Construct a very simple framework that reads in CSV with parameters and normal mu, sigma and generates a run list table (N = 10) - see #2 
- Run Hector for each entry in the run list, saving output (e.g. 2100 tracking data). N = ~100
- Basic visualizations (see whiteboard photo for initial ideas)
- Basic timing assessment

**February**

- Discuss with Kalyn and others and get feedback on process
- Think about parameter choices and joint PDFs
- Implement joint PDFs?

**March**

- Run new revised system, N = ~1000
- Timing assessment
- Results assessment
- Analysis development
- Begin to think about manuscript outline

**Comment by bpbond** [comment]
Adding: in January let's talk with @crvernon about his [existing Hector parameter analysis]( https://jgcri.slack.com/archives/C014L3U9F29/p1638285787042300).

**Comment by bpbond** [comment]
Chris:

I'll get that notebook that I mentioned in the hector-chat channel up on one of my personal repos.  This just shows how to build the process by:

- constructing a problem set (e.g., names and bounds of your parameters)
- generating sample data as defined by your problem set that provides global coverage of the parameter space (you don't want to get tricked by local minima which is why the global space is explored)
- running the model using your sample data (e.g., you have 10,000 samples representing a combination of your parameters that feeds into a run)
- passing your problem set, samples, and model outputs into a sensitivity analysis function that is compatible with your sampler method
- evaluate/rank your parameters based on their first/second order metrics which describe their contribution to the variance in your model outputs (e.g., find out when and if protuberance in in ocean heat diffusivity values influences the outcomes; this can also be evaluated over space, time, within module's of the software, etc.)
- Happy to discuss anytime

**Comment by leeyap** [comment]
Important Things we should talk about, in no particular order:

- [ ] Refactoring run loop, parallelization, pic setup
- [ ] Implementing new parameters
- [ ] Joint PDFs
- [ ] Variance analysis
- [ ] Review relative importance code

-----
- [ ] Science readings
- I want to make one list of sources so that I can organize my thoughts better and set up a schedule! We have a handful of readings floating out there and I want to get started in an organized way.
- [ ] Params + distributions
- [ ] SFD content

Feel free to edit this/comment other things I missed @bpbond 

Thanks!

**Comment by bpbond** [comment]
That looks good @leeyap , thanks. I've reorganized your bullets above to put them in (suggested) order of how we could tackle them, and agree that a more organized approach to readings is needed and will help.

Let's do some planning later today!
