### ISSUE TITLE
Upgrade to new calibrated Hector

### ISSUE THREAD

**Issue by bpbond** [JGCRI/trackingC#48]
@kdorheim has a calibrated v3 model that tracks observational [CO2], etc., very well.

**Comment by leeyap** [comment]
@bpbond does this just require a clean and rebuild of Hector on my machine, then re-running trackingC?

**Comment by bpbond** [comment]
Yes. @kdorheim is the calibrated version pushed to `v3_dev`?

**Comment by bpbond** [comment]
... doesn't look like it from the commit history?
