### ISSUE TITLE
Climate sensitivity ref

### ISSUE THREAD

**Issue by bpbond** [JGCRI/trackingC#50]
Updated reference with likely distribution: https://agupubs.onlinelibrary.wiley.com/doi/10.1029/2019RG000678

**Comment by leeyap** [comment]
> The 66% range is 2.6–3.9 K for our Baseline calculation and remains within 2.3–4.5 K under the robustness tests; corresponding 5–95% ranges are 2.3–4.7 K, bounded by 2.0–5.7 K (although such high-confidence ranges should be regarded more cautiously).

We have a lognormal of 3.25 +/- 0.65, so actually exactly 2.6-3.9 K. Can add this as an additional citation, though.

**Comment by leeyap** [comment]
Actually, our current citation is another Sherwood et al., just from 2020. Glad that they're consistent!

**Comment by bpbond** [comment]
Woot! Okay, thanks for checking.
