### ISSUE TITLE
Hector CO2 is still too low

### ISSUE THREAD

**Issue by leeyap** [JGCRI/trackingC#60]
In line with the "calibrated-Hector" parameters (below), I updated my model parameters to attempt and raise Hector CO2 to match historical output.

```
    BETA      Q10_RH   NPP_FLUX0  AERO_SCALE         ECS DIFFUSIVITY 
    0.160000    1.519490   55.911591    0.500000    2.724023    2.393617
```
My changed parameters:

Param | Old distribution | New distribution |
-- | -- | -- |
Beta | 0.54 +/- 0.03 (Keenan et al 2016)  | 0.28 +/- 0.1 (Jones et al 2018) |
Q10 | 2.0 +/- 1.0 (Davidson and Janssens, 2006)  | ~1.5 +/- 1.0~ |
AERO_SCALE | 1.01 +/- 0.23 (Smith et al 2020) | 0.5 +/- 0.23 |

I tried varying one at a time, and implementing all three. Despite best efforts, only one run made it through the filtering step on all four attempts... 

Here is the most recent graph, with all three new parameter values implemented. Note that the CO2 output from 1950 on was slightly higher with the original AERO_SCALE and Q10, but 1850-1950 will not budge. 

![image](https://user-images.githubusercontent.com/87151968/190004962-ee8a2ebd-95ae-4317-8d0d-c97c0b3c8429.png)

Not sure what the next steps here are. @bpbond: Help would be appreciated - thanks!

**Comment by bpbond** [comment]
@leeyap I am sitting here with @kdorheim and here are some ideas:
* What if we looked at _growth_ in atmospheric CO2 instead of absolute values? (I.e., the `diff` of each time series)
* What about if we say we're only using Mauna Launa record, i.e. ~1960 onward?

We might have some other suggestions too, but these are both simple to do and don't require you re-running anything model-wise. Could you try these two alternative filters?

**Comment by leeyap** [comment]
Just looking at the Mauna Loa record, that let more runs through, but now (as one might expect) future temperature is really high. These runs are still falling within the bounds of the CMIP max, but are much higher than they were before.

![image](https://user-images.githubusercontent.com/87151968/190190058-1c8eec77-01dd-46c2-82f4-6170958f2d3a.png)

**Comment by bpbond** [comment]
Thanks for the quick look. Huh. This surprises me given @kdorheim 's v3 analysis results; Kalyn, thoughts?

>as one might expect

Why? 😕 Sorry if I'm being dense.

**Comment by leeyap** [comment]
Oh sorry, I just meant that since we cranked up the CO2, it makes sense to me that temperature is higher now!

**Comment by bpbond** [comment]
It sounds like you and @kdorheim got a chance to talk about next steps?

**Comment by leeyap** [comment]
@bpbond Yep, still trying out a few things.
