### ISSUE TITLE
Next week

### ISSUE THREAD

**Issue by bpbond** [JGCRI/trackingC#68]
Hi @leeyap just summarizing from memory, feel free to edit.

@bpbond will
* Work through a number of the reviewer responses and provide sample text / bullets, doing some research as needed
* Available for consult/coding on LP's work below

@leeyap will
* Implement ocean sink filter — parallels land sink filter
* Try different values of `GCP_SD_X` (the GCP standard deviation multiplier; maybe do 1.0, 2.0, 3.0?) and quantify percentage of runs failing at each level
* Remove the correlated-parameters code, so that ECS and ocean heat uptake are generated independently just like other parameters
* I feel like there was a fourth thing... 😕 

Does this look good?

**Comment by leeyap** [comment]
Looks good! Fourth thing may have been the future CO2 filter and checking on the Pangeo models.

**Comment by leeyap** [comment]
- Ocean sink implemented ✔️ 
- See below for fail percentages from the land and ocean sinks with varying SD multipliers
- ECS and Keff are no longer jointly distributed ✔️ 
- Future CO2 filter is... not working well. Because of the limited data we're working with, only SSP585 has reasonable bounds for a filtering step - otherwise, the other scenarios have just one or two data points to average, creating an extremely tight filter. 
     - Thoughts here could be to take the mean across models for each scenario and use the uncertainty from the SSP585 values?

SD_X | Land | Ocean |
-- | -- | --
1 | 100% fail | 99% fail |
2 | 89% fail | 91% fail |
3 | 68% fail | 85% fail |
4 | 41% fail | 77% fail |

**Comment by leeyap** [comment]
Agreed to both - thanks!

Are we set to do a large ensemble run now, or are there other technical things that need to get checked off first?

**Comment by bpbond** [comment]
I agree, it seems like we're at a good point to scale up and see what we have. What about doing a bigger but not maximum run, say 500 per SSP or something like that, running all the way through the analysis?

**Comment by leeyap** [comment]
On it 👍

**Comment by bpbond** [comment]
P.S. I pulled that 500 number out of the air. If it's an inconvenience (in terms of laptop bogging down), I'm sure running n=100-200 or something would be plenty to let us assess things.

**Comment by leeyap** [comment]
Update on the filtering step (_not_ including future CO2):

Of 2000 total runs, 254 passed the filter step, or ~12.7%
The distribution of passes by SSP:

> 1 ssp126    56
> 2 ssp245    71
> 3 ssp370    67
> 4 ssp585    60

Scaling to 10,000, that would leave us with 1270 viable runs. Approximating here:
> 1 ssp126    279
> 2 ssp245    356
> 3 ssp370    330
> 4 ssp585    304

This feels a little on the low side for number of runs, I think probably still acceptable but at the bottom of the range. We might want to think about scaling up slightly. (Just thinking in context, the 0.05% of the 24 million runs comes out to be about 10,000 viable runs, so if we crank up the filtering, we probably need to crank up the runs a bit). 

Thoughts + feedback very welcome!

**Comment by bpbond** [comment]
Interesting! Great to have these estimates.

>still acceptable but at the bottom of the range

That sounds right to me, and I agree about raising the number of runs somewhat, as long as we don't run into memory issues while processing. On the other hand (or rather, in addition) I would be reluctant to go above 3x for that GCP multiplier.

So basically, sounds good.

**Comment by leeyap** [comment]
Cool. I'll try a big run overnight tomorrow and can get into the weeds of processing on Wednesday. Hopefully get the figures + output numbers finalized so I can work on updating the analysis portion of the manuscript!

**Comment by bpbond** [comment]
FYI, I've gotten delayed on the responses--sincere apologies, I know I said by today--but will be ready before our meeting tomorrow.

**Comment by leeyap** [comment]
That's totally fine! I can review them tomorrow, or we can go over them briefly at our meeting, no problem at all.

**Comment by bpbond** [comment]
I'll have a good subset of responses drafted by lunchtime, if you want to take a look before we meet (totally optional, just fyi).
