### ISSUE TITLE
Lognormal distribution parameters

### ISSUE THREAD

**Issue by leeyap** [JGCRI/trackingC#7]
As it stands, the code for lognormal distributions for Q10 and ECS are:
```
"Q10" = rlnorm(100, meanlog = log(2.0), sdlog = 0.2),
"ECS" = rlnorm(100, meanlog = log(3.0), sdlog = 0.3)
```

This produces a reasonable distribution when plotted as a histogram. But, shouldn't the `sdlog` argument also need to be on a log scale? `log(0.2)` and `log(0.3)` are both negative numbers. 

We had originally picked 0.2 and 0.3 as standard deviations that were 10% of the mean. Would `sdlog` then be `0.1 * log(2.0)`?

Need to ask for help.

**Comment by leeyap** [comment]
Thanks to help from Abigail!

Using this resource: https://msalganik.wordpress.com/2017/01/21/making-sense-of-the-rlnorm-function-in-r/
And this help:

> If `z ~ N(0,1)`, then `μ + σz ~ N(μ, σ^2)`
> Then `X = e^(μ + σz)`
> The mean of a lognormal(μ, σ^2) is `e^(μ + ((σ^2)/2)))` and the median is `e^μ`
>
> So taking your guys’ example: 
“Q10" = rlnorm(100, meanlog = log(2.0), sdlog = 0.2)
>
> The mean of your sampled random data Q10 is gonna be mean=exp( log(2) + (0.2^2)/2) = 2.040403 although you may have to get a larger number of points than 100 to get close. So Like you’ve run that line of code and Rstudio has a Q10 vector of values now, then `mean(Q10) =2.040403`. Here, Q10 is the X in my little write up.
The corresponding Z in my write up will follow a normal distribution with mean log(2) and sd 0.2.
•	As an aside, it’s just a coincidence that mean(Q10) is close to 2, because your sdlog is small. If your sdlog was 2, for example, `mean(Q10)`=14.77811
•	For your ECS with meanlog=log(3) and sdlog=0.3, `mean(ECS`) = 3.138084, you can see it already starting to drift away from whatever you put inside your log().
 >
> So It sounds like you guys want there to be some defined mean of your Q10 sample, say 2. Ie you have a plain old vector of numbers labeled Q10 and when you take the mean with `mean(Q10)`, you want it to spit out 2. And similarly, you want `sd(Q10)` to spit out 0.1*2 
•	If that’s the case, I would just define those as R variables you’re changing and then do the needed reparameterization to get the meanlog, sdlog arguments to the rlnorm function right. Luckily the blog I linked to has that done, and you can double check everything in R.

Using the example from the blog post above, I wrote a function to get the correct parameter values in `rlnorm`.

Two notes:
1. In order to get a smooth distribution, I have to use at least 10,000 runs. This is going to whack up the computation time of my `run_hector` function.
2. If the sd is less than one, the ((σ^2)/2)) number is very small and the mean doesn't change much. This produces what looks like a normal distribution. So we'd have to have a standard deviation of at least 1.

**Comment by bpbond** [comment]
@leeyap Oh interesting, and big thanks to @abigailsnyder 👏 

 It's an interesting question— do we want the mean to be 2? But great to have this laid out!
